import type { Metadata } from "next";
import ClientProvider from "@/components/ClientProvider";
// import localFont from "next/font/local";
import "@/styles/globals.css";
import "@/styles/common.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const pretendard = localFont({
//   src: "../../public/fonts/PretendardVariable.woff2",
//   variable: "--font-pretendard",
//   display: "swap",
//   weight: "45 920",
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" className={`${pretendard.variable}`}>
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans+KR&display=swap"
          as="style"
        />
      </head>
      <body>
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
